districts = [{'State': 'Alaska', 'Seat': '1'}, {'State': 'Alabama', 'Seat': '1'}, {'State': 'Alabama', 'Seat': '2'},
             {'State': 'Alabama', 'Seat': '3'}, {'State': 'Alabama', 'Seat': '4'}, {'State': 'Alabama', 'Seat': '5'},
             {'State': 'Alabama', 'Seat': '6'}, {'State': 'Alabama', 'Seat': '7'}, {'State': 'Arkansas', 'Seat': '1'},
             {'State': 'Arkansas', 'Seat': '2'}, {'State': 'Arkansas', 'Seat': '3'}, {'State': 'Arkansas', 'Seat': '4'},
             {'State': 'Arizona', 'Seat': '1'}, {'State': 'Arizona', 'Seat': '2'}, {'State': 'Arizona', 'Seat': '3'},
             {'State': 'Arizona', 'Seat': '4'}, {'State': 'Arizona', 'Seat': '5'}, {'State': 'Arizona', 'Seat': '6'},
             {'State': 'Arizona', 'Seat': '7'}, {'State': 'Arizona', 'Seat': '8'}, {'State': 'Arizona', 'Seat': '9'},
             {'State': 'California', 'Seat': '1'}, {'State': 'California', 'Seat': '2'},
             {'State': 'California', 'Seat': '3'}, {'State': 'California', 'Seat': '4'},
             {'State': 'California', 'Seat': '5'}, {'State': 'California', 'Seat': '6'},
             {'State': 'California', 'Seat': '7'}, {'State': 'California', 'Seat': '8'},
             {'State': 'California', 'Seat': '9'}, {'State': 'California', 'Seat': '10'},
             {'State': 'California', 'Seat': '11'}, {'State': 'California', 'Seat': '12'},
             {'State': 'California', 'Seat': '13'}, {'State': 'California', 'Seat': '14'},
             {'State': 'California', 'Seat': '15'}, {'State': 'California', 'Seat': '16'},
             {'State': 'California', 'Seat': '17'}, {'State': 'California', 'Seat': '18'},
             {'State': 'California', 'Seat': '19'}, {'State': 'California', 'Seat': '20'},
             {'State': 'California', 'Seat': '21'}, {'State': 'California', 'Seat': '22'},
             {'State': 'California', 'Seat': '23'}, {'State': 'California', 'Seat': '24'},
             {'State': 'California', 'Seat': '25'}, {'State': 'California', 'Seat': '26'},
             {'State': 'California', 'Seat': '27'}, {'State': 'California', 'Seat': '28'},
             {'State': 'California', 'Seat': '29'}, {'State': 'California', 'Seat': '30'},
             {'State': 'California', 'Seat': '31'}, {'State': 'California', 'Seat': '32'},
             {'State': 'California', 'Seat': '33'}, {'State': 'California', 'Seat': '34'},
             {'State': 'California', 'Seat': '35'}, {'State': 'California', 'Seat': '36'},
             {'State': 'California', 'Seat': '37'}, {'State': 'California', 'Seat': '38'},
             {'State': 'California', 'Seat': '39'}, {'State': 'California', 'Seat': '40'},
             {'State': 'California', 'Seat': '41'}, {'State': 'California', 'Seat': '42'},
             {'State': 'California', 'Seat': '43'}, {'State': 'California', 'Seat': '44'},
             {'State': 'California', 'Seat': '45'}, {'State': 'California', 'Seat': '46'},
             {'State': 'California', 'Seat': '47'}, {'State': 'California', 'Seat': '48'},
             {'State': 'California', 'Seat': '49'}, {'State': 'California', 'Seat': '50'},
             {'State': 'California', 'Seat': '51'}, {'State': 'California', 'Seat': '52'},
             {'State': 'Colorado', 'Seat': '1'}, {'State': 'Colorado', 'Seat': '2'}, {'State': 'Colorado', 'Seat': '3'},
             {'State': 'Colorado', 'Seat': '4'}, {'State': 'Colorado', 'Seat': '5'}, {'State': 'Colorado', 'Seat': '6'},
             {'State': 'Colorado', 'Seat': '7'}, {'State': 'Colorado', 'Seat': '8'},
             {'State': 'Connecticut', 'Seat': '1'}, {'State': 'Connecticut', 'Seat': '2'},
             {'State': 'Connecticut', 'Seat': '3'}, {'State': 'Connecticut', 'Seat': '4'},
             {'State': 'Connecticut', 'Seat': '5'}, {'State': 'Delaware', 'Seat': '1'},
             {'State': 'Florida', 'Seat': '1'}, {'State': 'Florida', 'Seat': '2'}, {'State': 'Florida', 'Seat': '3'},
             {'State': 'Florida', 'Seat': '4'}, {'State': 'Florida', 'Seat': '5'}, {'State': 'Florida', 'Seat': '6'},
             {'State': 'Florida', 'Seat': '7'}, {'State': 'Florida', 'Seat': '8'}, {'State': 'Florida', 'Seat': '9'},
             {'State': 'Florida', 'Seat': '10'}, {'State': 'Florida', 'Seat': '11'}, {'State': 'Florida', 'Seat': '12'},
             {'State': 'Florida', 'Seat': '13'}, {'State': 'Florida', 'Seat': '14'}, {'State': 'Florida', 'Seat': '15'},
             {'State': 'Florida', 'Seat': '16'}, {'State': 'Florida', 'Seat': '17'}, {'State': 'Florida', 'Seat': '18'},
             {'State': 'Florida', 'Seat': '19'}, {'State': 'Florida', 'Seat': '20'}, {'State': 'Florida', 'Seat': '21'},
             {'State': 'Florida', 'Seat': '22'}, {'State': 'Florida', 'Seat': '23'}, {'State': 'Florida', 'Seat': '24'},
             {'State': 'Florida', 'Seat': '25'}, {'State': 'Florida', 'Seat': '26'}, {'State': 'Florida', 'Seat': '27'},
             {'State': 'Florida', 'Seat': '28'}, {'State': 'Georgia', 'Seat': '1'}, {'State': 'Georgia', 'Seat': '2'},
             {'State': 'Georgia', 'Seat': '3'}, {'State': 'Georgia', 'Seat': '4'}, {'State': 'Georgia', 'Seat': '5'},
             {'State': 'Georgia', 'Seat': '6'}, {'State': 'Georgia', 'Seat': '7'}, {'State': 'Georgia', 'Seat': '8'},
             {'State': 'Georgia', 'Seat': '9'}, {'State': 'Georgia', 'Seat': '10'}, {'State': 'Georgia', 'Seat': '11'},
             {'State': 'Georgia', 'Seat': '12'}, {'State': 'Georgia', 'Seat': '13'}, {'State': 'Georgia', 'Seat': '14'},
             {'State': 'Hawaii', 'Seat': '1'}, {'State': 'Hawaii', 'Seat': '2'}, {'State': 'Iowa', 'Seat': '1'},
             {'State': 'Iowa', 'Seat': '2'}, {'State': 'Iowa', 'Seat': '3'}, {'State': 'Iowa', 'Seat': '4'},
             {'State': 'Idaho', 'Seat': '1'}, {'State': 'Idaho', 'Seat': '2'}, {'State': 'Illinois', 'Seat': '1'},
             {'State': 'Illinois', 'Seat': '2'}, {'State': 'Illinois', 'Seat': '3'}, {'State': 'Illinois', 'Seat': '4'},
             {'State': 'Illinois', 'Seat': '5'}, {'State': 'Illinois', 'Seat': '6'}, {'State': 'Illinois', 'Seat': '7'},
             {'State': 'Illinois', 'Seat': '8'}, {'State': 'Illinois', 'Seat': '9'},
             {'State': 'Illinois', 'Seat': '10'}, {'State': 'Illinois', 'Seat': '11'},
             {'State': 'Illinois', 'Seat': '12'}, {'State': 'Illinois', 'Seat': '13'},
             {'State': 'Illinois', 'Seat': '14'}, {'State': 'Illinois', 'Seat': '15'},
             {'State': 'Illinois', 'Seat': '16'}, {'State': 'Illinois', 'Seat': '17'},
             {'State': 'Indiana', 'Seat': '1'}, {'State': 'Indiana', 'Seat': '2'}, {'State': 'Indiana', 'Seat': '3'},
             {'State': 'Indiana', 'Seat': '4'}, {'State': 'Indiana', 'Seat': '5'}, {'State': 'Indiana', 'Seat': '6'},
             {'State': 'Indiana', 'Seat': '7'}, {'State': 'Indiana', 'Seat': '8'}, {'State': 'Indiana', 'Seat': '9'},
             {'State': 'Kansas', 'Seat': '1'}, {'State': 'Kansas', 'Seat': '2'}, {'State': 'Kansas', 'Seat': '3'},
             {'State': 'Kansas', 'Seat': '4'}, {'State': 'Kentucky', 'Seat': '1'}, {'State': 'Kentucky', 'Seat': '2'},
             {'State': 'Kentucky', 'Seat': '3'}, {'State': 'Kentucky', 'Seat': '4'}, {'State': 'Kentucky', 'Seat': '5'},
             {'State': 'Kentucky', 'Seat': '6'}, {'State': 'Louisiana', 'Seat': '1'},
             {'State': 'Louisiana', 'Seat': '2'}, {'State': 'Louisiana', 'Seat': '3'},
             {'State': 'Louisiana', 'Seat': '4'}, {'State': 'Louisiana', 'Seat': '5'},
             {'State': 'Louisiana', 'Seat': '6'}, {'State': 'Massachusetts', 'Seat': '1'},
             {'State': 'Massachusetts', 'Seat': '2'}, {'State': 'Massachusetts', 'Seat': '3'},
             {'State': 'Massachusetts', 'Seat': '4'}, {'State': 'Massachusetts', 'Seat': '5'},
             {'State': 'Massachusetts', 'Seat': '6'}, {'State': 'Massachusetts', 'Seat': '7'},
             {'State': 'Massachusetts', 'Seat': '8'}, {'State': 'Massachusetts', 'Seat': '9'},
             {'State': 'Maryland', 'Seat': '1'}, {'State': 'Maryland', 'Seat': '2'}, {'State': 'Maryland', 'Seat': '3'},
             {'State': 'Maryland', 'Seat': '4'}, {'State': 'Maryland', 'Seat': '5'}, {'State': 'Maryland', 'Seat': '6'},
             {'State': 'Maryland', 'Seat': '7'}, {'State': 'Maryland', 'Seat': '8'}, {'State': 'Maine', 'Seat': '1'},
             {'State': 'Maine', 'Seat': '2'}, {'State': 'Michigan', 'Seat': '1'}, {'State': 'Michigan', 'Seat': '2'},
             {'State': 'Michigan', 'Seat': '3'}, {'State': 'Michigan', 'Seat': '4'}, {'State': 'Michigan', 'Seat': '5'},
             {'State': 'Michigan', 'Seat': '6'}, {'State': 'Michigan', 'Seat': '7'}, {'State': 'Michigan', 'Seat': '8'},
             {'State': 'Michigan', 'Seat': '9'}, {'State': 'Michigan', 'Seat': '10'},
             {'State': 'Michigan', 'Seat': '11'}, {'State': 'Michigan', 'Seat': '12'},
             {'State': 'Michigan', 'Seat': '13'}, {'State': 'Minnesota', 'Seat': '1'},
             {'State': 'Minnesota', 'Seat': '2'}, {'State': 'Minnesota', 'Seat': '3'},
             {'State': 'Minnesota', 'Seat': '4'}, {'State': 'Minnesota', 'Seat': '5'},
             {'State': 'Minnesota', 'Seat': '6'}, {'State': 'Minnesota', 'Seat': '7'},
             {'State': 'Minnesota', 'Seat': '8'}, {'State': 'Missouri', 'Seat': '1'},
             {'State': 'Missouri', 'Seat': '2'}, {'State': 'Missouri', 'Seat': '3'}, {'State': 'Missouri', 'Seat': '4'},
             {'State': 'Missouri', 'Seat': '5'}, {'State': 'Missouri', 'Seat': '6'}, {'State': 'Missouri', 'Seat': '7'},
             {'State': 'Missouri', 'Seat': '8'}, {'State': 'Mississippi', 'Seat': '1'},
             {'State': 'Mississippi', 'Seat': '2'}, {'State': 'Mississippi', 'Seat': '3'},
             {'State': 'Mississippi', 'Seat': '4'}, {'State': 'Montana', 'Seat': '1'},
             {'State': 'Montana', 'Seat': '2'}, {'State': 'North Carolina', 'Seat': '1'},
             {'State': 'North Carolina', 'Seat': '2'}, {'State': 'North Carolina', 'Seat': '3'},
             {'State': 'North Carolina', 'Seat': '4'}, {'State': 'North Carolina', 'Seat': '5'},
             {'State': 'North Carolina', 'Seat': '6'}, {'State': 'North Carolina', 'Seat': '7'},
             {'State': 'North Carolina', 'Seat': '8'}, {'State': 'North Carolina', 'Seat': '9'},
             {'State': 'North Carolina', 'Seat': '10'}, {'State': 'North Carolina', 'Seat': '11'},
             {'State': 'North Carolina', 'Seat': '12'}, {'State': 'North Carolina', 'Seat': '13'},
             {'State': 'North Carolina', 'Seat': '14'}, {'State': 'North Dakota', 'Seat': '1'},
             {'State': 'Nebraska', 'Seat': '1'}, {'State': 'Nebraska', 'Seat': '2'}, {'State': 'Nebraska', 'Seat': '3'},
             {'State': 'New Hampshire', 'Seat': '1'}, {'State': 'New Hampshire', 'Seat': '2'},
             {'State': 'New Jersey', 'Seat': '1'}, {'State': 'New Jersey', 'Seat': '2'},
             {'State': 'New Jersey', 'Seat': '3'}, {'State': 'New Jersey', 'Seat': '4'},
             {'State': 'New Jersey', 'Seat': '5'}, {'State': 'New Jersey', 'Seat': '6'},
             {'State': 'New Jersey', 'Seat': '7'}, {'State': 'New Jersey', 'Seat': '8'},
             {'State': 'New Jersey', 'Seat': '9'}, {'State': 'New Jersey', 'Seat': '10'},
             {'State': 'New Jersey', 'Seat': '11'}, {'State': 'New Jersey', 'Seat': '12'},
             {'State': 'New Mexico', 'Seat': '1'}, {'State': 'New Mexico', 'Seat': '2'},
             {'State': 'New Mexico', 'Seat': '3'}, {'State': 'Nevada', 'Seat': '1'}, {'State': 'Nevada', 'Seat': '2'},
             {'State': 'Nevada', 'Seat': '3'}, {'State': 'Nevada', 'Seat': '4'}, {'State': 'New York', 'Seat': '1'},
             {'State': 'New York', 'Seat': '2'}, {'State': 'New York', 'Seat': '3'}, {'State': 'New York', 'Seat': '4'},
             {'State': 'New York', 'Seat': '5'}, {'State': 'New York', 'Seat': '6'}, {'State': 'New York', 'Seat': '7'},
             {'State': 'New York', 'Seat': '8'}, {'State': 'New York', 'Seat': '9'},
             {'State': 'New York', 'Seat': '10'}, {'State': 'New York', 'Seat': '11'},
             {'State': 'New York', 'Seat': '12'}, {'State': 'New York', 'Seat': '13'},
             {'State': 'New York', 'Seat': '14'}, {'State': 'New York', 'Seat': '15'},
             {'State': 'New York', 'Seat': '16'}, {'State': 'New York', 'Seat': '17'},
             {'State': 'New York', 'Seat': '18'}, {'State': 'New York', 'Seat': '19'},
             {'State': 'New York', 'Seat': '20'}, {'State': 'New York', 'Seat': '21'},
             {'State': 'New York', 'Seat': '22'}, {'State': 'New York', 'Seat': '23'},
             {'State': 'New York', 'Seat': '24'}, {'State': 'New York', 'Seat': '25'},
             {'State': 'New York', 'Seat': '26'}, {'State': 'Ohio', 'Seat': '1'}, {'State': 'Ohio', 'Seat': '2'},
             {'State': 'Ohio', 'Seat': '3'}, {'State': 'Ohio', 'Seat': '4'}, {'State': 'Ohio', 'Seat': '5'},
             {'State': 'Ohio', 'Seat': '6'}, {'State': 'Ohio', 'Seat': '7'}, {'State': 'Ohio', 'Seat': '8'},
             {'State': 'Ohio', 'Seat': '9'}, {'State': 'Ohio', 'Seat': '10'}, {'State': 'Ohio', 'Seat': '11'},
             {'State': 'Ohio', 'Seat': '12'}, {'State': 'Ohio', 'Seat': '13'}, {'State': 'Ohio', 'Seat': '14'},
             {'State': 'Ohio', 'Seat': '15'}, {'State': 'Oklahoma', 'Seat': '1'}, {'State': 'Oklahoma', 'Seat': '2'},
             {'State': 'Oklahoma', 'Seat': '3'}, {'State': 'Oklahoma', 'Seat': '4'}, {'State': 'Oklahoma', 'Seat': '5'},
             {'State': 'Oregon', 'Seat': '1'}, {'State': 'Oregon', 'Seat': '2'}, {'State': 'Oregon', 'Seat': '3'},
             {'State': 'Oregon', 'Seat': '4'}, {'State': 'Oregon', 'Seat': '5'}, {'State': 'Oregon', 'Seat': '6'},
             {'State': 'Pennsylvania', 'Seat': '1'}, {'State': 'Pennsylvania', 'Seat': '2'},
             {'State': 'Pennsylvania', 'Seat': '3'}, {'State': 'Pennsylvania', 'Seat': '4'},
             {'State': 'Pennsylvania', 'Seat': '5'}, {'State': 'Pennsylvania', 'Seat': '6'},
             {'State': 'Pennsylvania', 'Seat': '7'}, {'State': 'Pennsylvania', 'Seat': '8'},
             {'State': 'Pennsylvania', 'Seat': '9'}, {'State': 'Pennsylvania', 'Seat': '10'},
             {'State': 'Pennsylvania', 'Seat': '11'}, {'State': 'Pennsylvania', 'Seat': '12'},
             {'State': 'Pennsylvania', 'Seat': '13'}, {'State': 'Pennsylvania', 'Seat': '14'},
             {'State': 'Pennsylvania', 'Seat': '15'}, {'State': 'Pennsylvania', 'Seat': '16'},
             {'State': 'Pennsylvania', 'Seat': '17'}, {'State': 'Rhode Island', 'Seat': '1'},
             {'State': 'Rhode Island', 'Seat': '2'}, {'State': 'South Carolina', 'Seat': '1'},
             {'State': 'South Carolina', 'Seat': '2'}, {'State': 'South Carolina', 'Seat': '3'},
             {'State': 'South Carolina', 'Seat': '4'}, {'State': 'South Carolina', 'Seat': '5'},
             {'State': 'South Carolina', 'Seat': '6'}, {'State': 'South Carolina', 'Seat': '7'},
             {'State': 'South Dakota', 'Seat': '1'}, {'State': 'Tennessee', 'Seat': '1'},
             {'State': 'Tennessee', 'Seat': '2'}, {'State': 'Tennessee', 'Seat': '3'},
             {'State': 'Tennessee', 'Seat': '4'}, {'State': 'Tennessee', 'Seat': '5'},
             {'State': 'Tennessee', 'Seat': '6'}, {'State': 'Tennessee', 'Seat': '7'},
             {'State': 'Tennessee', 'Seat': '8'}, {'State': 'Tennessee', 'Seat': '9'}, {'State': 'Texas', 'Seat': '1'},
             {'State': 'Texas', 'Seat': '2'}, {'State': 'Texas', 'Seat': '3'}, {'State': 'Texas', 'Seat': '4'},
             {'State': 'Texas', 'Seat': '5'}, {'State': 'Texas', 'Seat': '6'}, {'State': 'Texas', 'Seat': '7'},
             {'State': 'Texas', 'Seat': '8'}, {'State': 'Texas', 'Seat': '9'}, {'State': 'Texas', 'Seat': '10'},
             {'State': 'Texas', 'Seat': '11'}, {'State': 'Texas', 'Seat': '12'}, {'State': 'Texas', 'Seat': '13'},
             {'State': 'Texas', 'Seat': '14'}, {'State': 'Texas', 'Seat': '15'}, {'State': 'Texas', 'Seat': '16'},
             {'State': 'Texas', 'Seat': '17'}, {'State': 'Texas', 'Seat': '18'}, {'State': 'Texas', 'Seat': '19'},
             {'State': 'Texas', 'Seat': '20'}, {'State': 'Texas', 'Seat': '21'}, {'State': 'Texas', 'Seat': '22'},
             {'State': 'Texas', 'Seat': '23'}, {'State': 'Texas', 'Seat': '24'}, {'State': 'Texas', 'Seat': '25'},
             {'State': 'Texas', 'Seat': '26'}, {'State': 'Texas', 'Seat': '27'}, {'State': 'Texas', 'Seat': '28'},
             {'State': 'Texas', 'Seat': '29'}, {'State': 'Texas', 'Seat': '30'}, {'State': 'Texas', 'Seat': '31'},
             {'State': 'Texas', 'Seat': '32'}, {'State': 'Texas', 'Seat': '33'}, {'State': 'Texas', 'Seat': '34'},
             {'State': 'Texas', 'Seat': '35'}, {'State': 'Texas', 'Seat': '36'}, {'State': 'Texas', 'Seat': '37'},
             {'State': 'Texas', 'Seat': '38'}, {'State': 'Utah', 'Seat': '1'}, {'State': 'Utah', 'Seat': '2'},
             {'State': 'Utah', 'Seat': '3'}, {'State': 'Utah', 'Seat': '4'}, {'State': 'Virginia', 'Seat': '1'},
             {'State': 'Virginia', 'Seat': '2'}, {'State': 'Virginia', 'Seat': '3'}, {'State': 'Virginia', 'Seat': '4'},
             {'State': 'Virginia', 'Seat': '5'}, {'State': 'Virginia', 'Seat': '6'}, {'State': 'Virginia', 'Seat': '7'},
             {'State': 'Virginia', 'Seat': '8'}, {'State': 'Virginia', 'Seat': '9'},
             {'State': 'Virginia', 'Seat': '10'}, {'State': 'Virginia', 'Seat': '11'},
             {'State': 'Vermont', 'Seat': '1'}, {'State': 'Washington', 'Seat': '1'},
             {'State': 'Washington', 'Seat': '2'}, {'State': 'Washington', 'Seat': '3'},
             {'State': 'Washington', 'Seat': '4'}, {'State': 'Washington', 'Seat': '5'},
             {'State': 'Washington', 'Seat': '6'}, {'State': 'Washington', 'Seat': '7'},
             {'State': 'Washington', 'Seat': '8'}, {'State': 'Washington', 'Seat': '9'},
             {'State': 'Washington', 'Seat': '10'}, {'State': 'Wisconsin', 'Seat': '1'},
             {'State': 'Wisconsin', 'Seat': '2'}, {'State': 'Wisconsin', 'Seat': '3'},
             {'State': 'Wisconsin', 'Seat': '4'}, {'State': 'Wisconsin', 'Seat': '5'},
             {'State': 'Wisconsin', 'Seat': '6'}, {'State': 'Wisconsin', 'Seat': '7'},
             {'State': 'Wisconsin', 'Seat': '8'}, {'State': 'West Virginia', 'Seat': '1'},
             {'State': 'West Virginia', 'Seat': '2'}, {'State': 'Wyoming', 'Seat': '1'}]


us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))
